### ISSUE TITLE
NewSized API was removed

### ISSUE THREAD

**Issue by james-antill** [zeebo/blake3#10]
In this commit:

https://github.com/zeebo/blake3/commit/c2a53ed4a2081541f84651ff33b9b91fd3cf48bc

...you removed the NewSized() API, along with NewKeySized() which was added in the same set of commits on "that day".

Was that intentional?

**Comment by zeebo** [comment]
Yes. You can use

```go
var buf [N]byte
h.Output().Read(buf[:])
```

to read `N` bytes of output.
