### ISSUE TITLE
Is this repo faster than this https://github.com/lukechampine/blake3/?

### ISSUE THREAD

**Issue by hiqsociety** [zeebo/blake3#12]
https://github.com/lukechampine/blake3/

just curious. any downsides or tradeoffs between using lukechampine or zeebo?

**Comment by zeebo** [comment]
I'd hope they compute the same outputs (:smile:), so it comes down to which API you prefer and benchmarking for your use patterns.

Oh, and iirc they have AVX-512 support and I don't.

**Comment by hiqsociety** [comment]
> I'd hope they compute the same outputs (), so it comes down to which API you prefer and benchmarking for your use patterns.

Really? what makes u think the output will be different... oh... because it's written in pure golang...?

> 
> Oh, and iirc they have AVX-512 support and I don't.

how about speed? zeebo is faster? is AVX-512 important?

**Comment by zeebo** [comment]
> Really? what makes u think the output will be different... oh... because it's written in pure golang...?

Sorry, I was making a joke.

> how about speed? zeebo is faster? is AVX-512 important?

I don't know which is faster. Faster depends on many things, like message size for example. AVX-512 also only matters if you both have a processor with the instruction set (I don't) and your messages are large enough.

**Comment by hiqsociety** [comment]
can u do the benchmark? afterall, we just want the speed. 
is this version faster with avx-512? i have it on my server

**Comment by zeebo** [comment]
> can u do the benchmark? afterall, we just want the speed.

There are benchmark numbers posted in the README. They are from running on my home computer, so they will differ from your server. The only way to get benchmarks on your server is to run them yourself. 

> is this version faster with avx-512? i have it on my server

If your workload benefits from avx-512, it will be faster. My library does not do avx-512. The only way to know if this is the case for you is for you to run benchmarks. 

Performance is a difficult and nuanced thing that can't be reduced to one thing being faster than another on a single dimension.

**Comment by sergeevabc** [comment]
@zeebo, any chance you could produce a binary for Windows? I am an ordinary user w/o compiler. Alas, b3sum is [partly broken][1].

[1]: https://github.com/BLAKE3-team/BLAKE3/issues/78#issuecomment-801425510

**Comment by lukechampine** [comment]
@hiqsociety the tradeoff is that my asm-generation code is simpler and less sophisticated than this package. My goal was to make the code easy to review and thus more likely to make it into the stdlib someday. The downside is that it sacrifices some performance (and the asm is pretty bloated...although that's fixable). As zeebo mentioned, my implementation supports AVX-512, so it will be faster if you have that instruction set, but IIRC it's somewhat slower otherwise.

**Comment by zeebo** [comment]
> @zeebo, any chance you could produce a binary for Windows? I am an ordinary user w/o compiler. Alas, b3sum is [partly broken](https://github.com/BLAKE3-team/BLAKE3/issues/78#issuecomment-801425510).

Sorry, but I'm only interested in maintaining a library, not any binaries. Also, that doesn't really have anything to do with this issue.

Also also, I think the question has been sufficiently answered. Thanks to @lukechampine for also providing input.
