### ISSUE TITLE
i'm surprised i cant find a golang binding to blake3 online. 

### ISSUE THREAD

**Issue by hiqsociety** [zeebo/blake3#16]
i'm surprised i cant find a golang binding to blake3 online. how come no one has come up with it yet?

**Comment by zeebo** [comment]
I'm not sure how this repository isn't that. Can you describe in more detail what you're looking for?

**Comment by hiqsociety** [comment]
minimal memory, highest speed possible of blake3.
not sure if this is now better than lukechampion's blake3 now? coz i saw some improvement of this repo over time.

is it fastest available golang blake3? (mem efficient is kind of important too.) i'm using lukechampions blake3 but the mem is using "kind of a lot" though it does get reclaimed

**Comment by zeebo** [comment]
Again, as said in #15 (and I now noticed that you also opened https://github.com/lukechampine/blake3/issues/11), those comparisons were answered in #12. I'm sorry, but I'm not going to benchmark your workloads for you.
