### ISSUE TITLE
Incorrect BlockSize value

### ISSUE THREAD

**Issue by dchest** [zeebo/blake3#19]
hash.Hash is an internal block size of the hash function, that is the number of bits of input a hash function takes before applying the compression function. It is 512 bits (64 bytes) for BLAKE3.

Sources, apart from the BLAKE3 paper:

* https://github.com/BLAKE3-team/BLAKE3/blob/4e84c8c7ae3da71d3aff5ba54d8ffa39a9b90fa0/c/blake3.h#L14
* https://github.com/lukechampine/blake3/blob/v1.1.7/blake3.go#L144

This value is used for other cryptographic functions derived from the hash function, e.g. in HMAC and by the consequence, PBKDF2 (not that anyone would use HMAC or PBKDF2 with BLAKE3, but still.)

To answer the question in the TODO:
```
func (h *Hasher) BlockSize() int {
	// TODO: is there a downside to picking this large size?
	return 8192
}
```

Yes, the downside is that it becomes non-standard BLAKE3 :-)

BTW, thanks for the nice and fast implementation!

**Comment by zeebo** [comment]
Shoot. I thought the BlockSize method on the interface was only used to pick an appropriate size to write, not that it had cryptographic implications, but it is indeed inspected for HMAC and PBKDF2. Thanks for catching this.
