### ISSUE TITLE
Improve Hash interface 

### ISSUE THREAD

**Issue by udf2457** [zeebo/blake3#22]
At the moment the Hash interface returned from New is quite basic.

It would be nice if it returned the same as the standard library Hash interface, in particular it would be useful if it returned an embedded `io.Writer` interface so that `blake3` can be used with a stream input (i.e. `io.Copy`).

At the moment (as far as I can tell), the only way to hash files with `blake3` is the old-school iterative buffer method.  This is not very efficient, both in terms of clean coding and technical implementation.

**Comment by zeebo** [comment]
Haha, don't be so hard on yourself! Glad I could be of some help. :smile:
