### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [zeebo/blake3#3]
Dear Jeff,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by zeebo** [comment]
This is just a library. There's no executable to build.

**Comment by xkortex** [comment]
Here's a dirt-simple cli implementation. (c) unlicense, I don't care. 

You might need to tweak it to get it to work on Windows, I don't play that way ;)

```go
package main

import (
	"encoding/hex"
	"flag"
	"fmt"
	"github.com/zeebo/blake3"
	"io"
	"log"
	"os"
)

var targets []string

func toHex(data []byte) string { return hex.EncodeToString(data) }

func Blake3File(target string) {
	f, err := os.Open(target)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	h := blake3.New()

	if _, err := io.Copy(h, f); err != nil {
		log.Fatal(err)
	}
	out := toHex(h.Sum(nil))
	fmt.Println(out)
}

func init() {

	flag.Parse()
	targets = flag.Args()

	// quit if no target can be determined
	if len(targets) == 0 {
		log.Fatal("Must provide at least one target file")
	}

}

func main() {
	// print the hash result for each targets
	for _, target := range targets {
		fmt.Println(target)
		Blake3File(target)
	}
}

```

**Comment by zeebo** [comment]
Sorry if you don't have a Go compiler. I don't really want to be in the business of maintaining builds of binaries or their implementations.

Fortunately, it's easy to get the compiler, and the above comment shows that you can write something that works in a small amount of code. So I recommend diving in to the wonderful world of programming and giving it a shot. :smile:

**Comment by sergeevabc** [comment]
@zeebo, imagine Jobs saying “become an engineer and use our DIY iPhone kit”.
Well, then let’s wait for another Prometheus to bring another fire to the people.

**Comment by zeebo** [comment]
I'm sorry that I can't do this for you. Good luck.

**Comment by KEANO89** [comment]
@sergeevabc There are windows binaries provided by the official repo (e.g. [release 0.3.5](https://github.com/BLAKE3-team/BLAKE3/releases/tag/0.3.5))

**Comment by sergeevabc** [comment]
@KEANO89, alas, a reference implementation of Blake3 works very bad on my end. I have reported that [many times](https://github.com/BLAKE3-team/BLAKE3/issues/78#issuecomment-801425510), but its developers lack empathy. That's why I switched to searching for alternative implementations. Fortunately, they exists. Let me list a few for those who are looking for a solution like I did.

GUI:
* [CHK](https://compressme.net/)
* [RapidCRCUnicode](https://www.ov2.eu/programs/rapidcrc-unicode)
* [TurboSFV](https://turbosfv.com/)

CLI:
* A. Baker [filehash](https://brainwavecc.com/brainwave-utilities/)
* D. Dulesov [hashsum](https://github.com/ddulesov/hashsum)
* T. Reichardt [7zipZSTD](https://github.com/mcmilk/7-Zip-zstd/blob/master/C/hashes/blake3.c)
* M. Idrassi [dirhash](https://github.com/idrassi/DirHash)
