### ISSUE TITLE
Non-AVX2 version slower than BLAKE2b

### ISSUE THREAD

**Issue by andrius4669** [zeebo/blake3#9]
on my old-ish lappy without AVX2 instructions, this package ends up taking ~83% more ns/op compared to `blake2b` from `x/crypto`.
Not really sure if this only happens on my laptop, but I guess SSE4.1 version could be improved?

**Comment by zeebo** [comment]
I don't have access to any hardware that doesn't have avx2 but does have sse4.1. The issue I have is that I couldn't get the sse4.1 code to generate without instructions that I think also require avx2. That puts me in an unfortunate position.

If I had access to some hardware like that, I could work on making sure that the sse4.1 version works...

I wonder if any cloud providers have hardware like that.

**Comment by zeebo** [comment]
I wonder if I can use qemu or something for this?

**Comment by andrius4669** [comment]
QEMU probably would be okay for limiting cpuid feature set but im kinda wondering whether it'll actually properly limit instruction set and whether it'll actually act like CPU not supporting these instructions for performance tuning reasons.
I went thru my VPSes and there's one with avx but without avx2 (Intel(R) Xeon(R) CPU E3-1240), it's running some unimportant stuff & I could provide shell account for that if that would work for you.

**Comment by zeebo** [comment]
Shell access would be amazing.

My public key is `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKhk5rYGto/l+lizVVfwF/liGNScMCGtnVCbkQccVQuP`

If you would prefer to send me some other way to log in, you can reach me through https://keybase.io/zeebo. Let me know if either of these options don't work for  you.

**Comment by andrius4669** [comment]
`zeebo@usx1.andrius4669.org` should probably work.
it's oldish debian on openvz installation but with upstream golang automatically updated w/ cronjob+custom script downloading official linux release from main golang site.
only thing what could affect perf testing a bit would be i2p, its tuned to not eat too much but it still eats a bit, hopefully that won't get in a way.
tell me if anything else needs to be installed or changed or if something doesn't work.

**Comment by zeebo** [comment]
As an update, I managed to get the code running on that host you provided (thanks again!). I have to do some restructuring, but the SSE4.1 code executed without problems.

It looks like the machine wasn't very quiet in terms of cpu usage, so the benchmarks were a bit spotty, and I didn't want to hog up all the cpu away from whatever was running, so I can't yet comment on what the speed will be like.

**Comment by andrius4669** [comment]
I somehow completely overlooked the fact that it's OpenVZ VPS when writing "only thing what could affect perf testing a bit would be i2p".
It's certainly not the only thing running in that machine, especially since OVZ VPSes tend to be sorta oversubscribed.
iirc for perf testing of this sort supercop recommends running on bare and disabling turbo boost...
having said that it should still be usable to some extent. don't be afraid to run some tests if they don't run for too long (minute or few shouldn't be too long.. I think? I remember compiling some stuff on it and it was fine. not that I consider that to be long enough to smooth it out).

**Comment by zeebo** [comment]
Hopefully this is now fixed on v0.1.0. Please reopen if not.

**Comment by andrius4669** [comment]
It's now pretty much same (but not really better) on my laptop as blake2b perf-wise, so yep, can be considered fixed.
Thanks!

**Comment by andrius4669** [comment]
on that VPS it does look quite better than blake2b. interesting.
but it's pretty much a tie on my laptop (often blake2b is faster by a little bit, sometimes blake3 is).
anyway, that VPS is probably more representative.
just wanted to elaborate a bit, sorry for spamming fixed issue.

**Comment by zeebo** [comment]
That's some interesting info. Thanks for sharing and don't worry about spamming :)

Hmm... if you're up for it, is it possible to try out the speed of the upstream rust blake3 repository? I'm interested in how it compares to this one (single threaded if possible) to see if I'm missing some optimization.
